# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimatedTransitions' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimatedTransitions
	pod 'SnapKit', '~> 5.6.0'

end

target 'AT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AT

end
